services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: univanxx/mlops_repo
    ports:
      - 127.0.0.1:5000:5000
    working_dir: /flask_app
    
  db:
    image: postgres
    environment:
      POSTGRES_DB: "mlops_db"
      POSTGRES_USER: "bestuser"
      POSTGRES_PASSWORD: "hellokek"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
